name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Build Docker image
      run: |
        docker build --build-arg DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} \
                     --build-arg DISCORD_CHANNEL_ID=${{ secrets.DISCORD_CHANNEL_ID }} \
                     --build-arg DISCORD_CHANNEL_ID=${{ secrets.XTB_USER_ID }} \
                     --build-arg DISCORD_CHANNEL_ID=${{ secrets.XTB_PASSWORD }} \
                     -t live-trading-bot:latest .

    - name: Login to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: |
        echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin

    - name: Push Docker image
      run: |
        docker tag live-trading-bot:latest bixor/live-trading-bot:latest
        docker push bixor/live-trading-bot:latest

    - name: SSH to EC2 and deploy
      env:
       EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
       EC2_HOST: ${{ secrets.EC2_HOST }} 
       EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }} 
      run: |
       echo "$EC2_SSH_KEY" > private_key.pem
       chmod 600 private_key.pem
       ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USERNAME@$EC2_HOST << 'EOF'
         docker pull bixor/live-trading-bot:latest
         docker stop live-trading-bot || true 
         docker rm live-trading-bot || true 
         docker run -d --name live-trading-bot -p 5001:5000 bixor/live-trading-bot:latest
       EOF
